/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **userdetails**
   * - Table in database
   */
  export namespace userdetails {
    export type Table = 'userdetails';
    export interface Selectable {
      /**
      * **userdetails.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('userdetails_id_seq'::regclass)`
      */
      id: number;
      /**
      * **userdetails.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **userdetails.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name: string | null;
      /**
      * **userdetails.bio**
      * - `varchar` in database
      * - Nullable, no default
      */
      bio: string | null;
      /**
      * **userdetails.profilepicture**
      * - `varchar` in database
      * - Nullable, no default
      */
      profilepicture: string | null;
      /**
      * **userdetails.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat: Date | null;
      /**
      * **userdetails.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **userdetails.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('userdetails_id_seq'::regclass)`
      */
      id: number;
      /**
      * **userdetails.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **userdetails.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name: string | null;
      /**
      * **userdetails.bio**
      * - `varchar` in database
      * - Nullable, no default
      */
      bio: string | null;
      /**
      * **userdetails.profilepicture**
      * - `varchar` in database
      * - Nullable, no default
      */
      profilepicture: string | null;
      /**
      * **userdetails.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat: db.TimestampString | null;
      /**
      * **userdetails.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **userdetails.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('userdetails_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.bio**
      * - `varchar` in database
      * - Nullable, no default
      */
      bio?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.profilepicture**
      * - `varchar` in database
      * - Nullable, no default
      */
      profilepicture?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userdetails.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **userdetails.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('userdetails_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **userdetails.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **userdetails.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userdetails.bio**
      * - `varchar` in database
      * - Nullable, no default
      */
      bio?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userdetails.profilepicture**
      * - `varchar` in database
      * - Nullable, no default
      */
      profilepicture?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userdetails.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userdetails.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **userdetails.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('userdetails_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **userdetails.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **userdetails.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userdetails.bio**
      * - `varchar` in database
      * - Nullable, no default
      */
      bio?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userdetails.profilepicture**
      * - `varchar` in database
      * - Nullable, no default
      */
      profilepicture?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userdetails.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userdetails.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'userdetails_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **users**
   * - Table in database
   */
  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password: string | null;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username: string | null;
      /**
      * **users.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat: Date | null;
      /**
      * **users.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password: string | null;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username: string | null;
      /**
      * **users.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat: db.TimestampString | null;
      /**
      * **users.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.createdat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      createdat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.updatedat**
      * - `timestamp` in database
      * - Nullable, no default
      */
      updatedat?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'users_id_username_key' | 'users_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = userdetails.Table | users.Table;
    export type Selectable = userdetails.Selectable | users.Selectable;
    export type JSONSelectable = userdetails.JSONSelectable | users.JSONSelectable;
    export type Whereable = userdetails.Whereable | users.Whereable;
    export type Insertable = userdetails.Insertable | users.Insertable;
    export type Updatable = userdetails.Updatable | users.Updatable;
    export type UniqueIndex = userdetails.UniqueIndex | users.UniqueIndex;
    export type Column = userdetails.Column | users.Column;
  
    export type AllBaseTables = [userdetails.Table, users.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [userdetails.Table, users.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "userdetails": userdetails.Selectable;
    "users": users.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "userdetails": userdetails.JSONSelectable;
    "users": users.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "userdetails": userdetails.Whereable;
    "users": users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "userdetails": userdetails.Insertable;
    "users": users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "userdetails": userdetails.Updatable;
    "users": users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "userdetails": userdetails.UniqueIndex;
    "users": users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "userdetails": userdetails.Column;
    "users": users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "userdetails": userdetails.SQL;
    "users": users.SQL;
  }[T];

}
